### ISSUE TITLE
EOL Tomboy?

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.gnome.Tomboy#2]
The development has stopped and they have moved to a new version called Tomboy-ng

See https://github.com/tomboy-notes/tomboy/commit/e7a27fbe4589b7190f95bacb3b073ac2e17ff455

I wonder if this should be EOL-ed or kept?

If it is the latter I can try to update the runtime, no guaranties.

**Comment by bbhtt** [comment]
cc @ramcq Hi, any thoughts?

**Comment by ramcq** [comment]
Tomboy-ng is a pretty different application and doesn't support sync to Tomdroid via https://github.com/grosjo/nextcloud-grauphel/ which I am using.

You're welcome to try a new runtime but I must warn you the build is pretty delicate, needing specific versions of mono and bindings etc.

As it speaks over the network to precisely one endpoint: my own server - I am not super worried about needing to update anything or stop using it. It's a pretty compelling use case for Flatpak just keeping everything the same, and keeping working. It doesn't need an EOL IMO.

**Comment by ramcq** [comment]
Oh actually it worked fine. 🤣 https://github.com/flathub/org.gnome.Tomboy/commit/3a7ea6e

**Comment by bbhtt** [comment]
> Oh actually it worked fine. rofl [3a7ea6e](https://github.com/flathub/org.gnome.Tomboy/commit/3a7ea6e)

I sent a concurrent PR 😅

**Comment by ramcq** [comment]
Sorry! We can merge and consider the other updates you made, I didn't check the dependencies.

**Comment by bbhtt** [comment]
No worries! I'll rebase on top of your changes. It has only the perl module upgrades.
